name: Setup Codespaces

on:
  push:
    branches:
      - main

jobs:
  setup-codespaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Codespaces
        uses: github/codespaces-setup-action@v2
        with:
          dotfiles: true
